"created notifications table -  nick Truong
aggie-coding-club/SecuroChat pull request #50
Opened 2023-10-27 00:13 UTC by NickTnc24

made  notifications table

2023-10-27 04:26 UTC, oliverkstalker requested changes
messag_id should reference messages table not conversations table, otherwise looks good

2023-10-29 23:39 UTC, NickTnc24 reviewed
done!

2023-11-01 05:32 UTC, carlosra0345 approved these changes
Nice work!

2023-11-01 05:32 UTC, carlosra0345 approved these changes

2023-11-01 05:33 UTC, carlosra0345 approved these changes

2023-11-01 05:34 UTC, merged